name: update laws
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # utc 00:00, tw 08:00

permissions:
  contents: write

jobs:
  update-laws:
    runs-on: ubuntu-latest
    steps:
      - name: setup babashka
        run: |
          curl -sL -o install-bb https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install-bb
          sudo ./install-bb

      - uses: actions/checkout@v3

      - name: fetch law jsons
        run: bb prepare-jsons

      - name: extract and process law jsons
        run: bb process-law-jsons

      - name: commit and push
        shell: bash {0}
        run: |
          git config --global user.name 'Taiwan Laws'
          git config --global user.email 'taiwan-laws@users.noreply.github.com'
          git add .
          git commit -m "updated @ $(date +%Y-%m-%d)" && \
            git tag v$(date +%Y.%m.%d) && \
            git push

